# 6FB Methodologies Workshop - Prometheus Configuration
# Comprehensive monitoring for ticket sales application

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: '6fb-methodologies'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Rules configuration
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # Next.js Application
  - job_name: '6fb-app'
    static_configs:
      - targets: ['app:3000']
    scrape_interval: 15s
    metrics_path: /api/metrics
    scrape_timeout: 10s
    honor_labels: true

  # PostgreSQL Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s
    metrics_path: /metrics
    params:
      target: ['postgres:5432']

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    metrics_path: /metrics

  # Nginx Reverse Proxy
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 30s
    metrics_path: /nginx_status
    scrape_timeout: 10s

  # Node Exporter (System Metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # cAdvisor (Container Metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # Alertmanager
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
    scrape_interval: 30s

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s
    metrics_path: /metrics

  # Custom Application Metrics
  - job_name: '6fb-custom-metrics'
    static_configs:
      - targets: ['app:3000']
    scrape_interval: 10s
    metrics_path: /api/metrics/custom
    scrape_timeout: 5s
    params:
      format: ['prometheus']

  # Webhook Endpoints Monitoring
  - job_name: '6fb-webhooks'
    static_configs:
      - targets: ['app:3000']
    scrape_interval: 60s
    metrics_path: /api/metrics/webhooks
    scrape_timeout: 10s

  # Health Check Endpoints
  - job_name: '6fb-health'
    static_configs:
      - targets: ['app:3000']
    scrape_interval: 15s
    metrics_path: /api/health
    scrape_timeout: 5s

# Remote write configuration (for long-term storage)
# remote_write:
#   - url: "https://your-prometheus-remote-write-endpoint"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
    path: /prometheus
    wal-compression: true